from setuptools import setup

setup(
    name='pyhfss_parser',
    version='0.0.0',
    packages=['', 'venv.Lib.site-packages.py', 'venv.Lib.site-packages.py._io', 'venv.Lib.site-packages.py._log',
              'venv.Lib.site-packages.py._code', 'venv.Lib.site-packages.py._path',
              'venv.Lib.site-packages.py._process', 'venv.Lib.site-packages.py._vendored_packages',
              'venv.Lib.site-packages.pip', 'venv.Lib.site-packages.pip._vendor',
              'venv.Lib.site-packages.pip._vendor.idna', 'venv.Lib.site-packages.pip._vendor.pytoml',
              'venv.Lib.site-packages.pip._vendor.certifi', 'venv.Lib.site-packages.pip._vendor.chardet',
              'venv.Lib.site-packages.pip._vendor.chardet.cli', 'venv.Lib.site-packages.pip._vendor.distlib',
              'venv.Lib.site-packages.pip._vendor.distlib._backport', 'venv.Lib.site-packages.pip._vendor.msgpack',
              'venv.Lib.site-packages.pip._vendor.urllib3', 'venv.Lib.site-packages.pip._vendor.urllib3.util',
              'venv.Lib.site-packages.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip._vendor.colorama', 'venv.Lib.site-packages.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'venv.Lib.site-packages.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip._vendor.progress', 'venv.Lib.site-packages.pip._vendor.requests',
              'venv.Lib.site-packages.pip._vendor.packaging', 'venv.Lib.site-packages.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip._vendor.webencodings', 'venv.Lib.site-packages.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip._internal', 'venv.Lib.site-packages.pip._internal.req',
              'venv.Lib.site-packages.pip._internal.vcs', 'venv.Lib.site-packages.pip._internal.utils',
              'venv.Lib.site-packages.pip._internal.models', 'venv.Lib.site-packages.pip._internal.commands',
              'venv.Lib.site-packages.pip._internal.operations', 'venv.Lib.site-packages.attr',
              'venv.Lib.site-packages.pluggy', 'venv.Lib.site-packages._pytest', 'venv.Lib.site-packages._pytest.mark',
              'venv.Lib.site-packages._pytest._code', 'venv.Lib.site-packages._pytest.config',
              'venv.Lib.site-packages._pytest.assertion', 'venv.Lib.site-packages.colorama',
              'venv.Lib.site-packages.atomicwrites', 'venv.Lib.site-packages.parsimonious',
              'venv.Lib.site-packages.parsimonious.tests', 'venv.Lib.site-packages.more_itertools',
              'venv.Lib.site-packages.more_itertools.tests', 'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip.req',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip.vcs',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip.utils',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip.compat',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip.models',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.distlib',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.colorama',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.progress',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.requests',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.requests.packages',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.requests.packages.chardet',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.requests.packages.urllib3',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.requests.packages.urllib3.util',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.requests.packages.urllib3.contrib',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.requests.packages.urllib3.packages',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.packaging',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.webencodings',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip.commands',
              'venv.Lib.site-packages.pip-9.0.1-py3.7.egg.pip.operations'],
    url='',
    license='MIT',
    author='Ariksu',
    author_email='ariksu@gmail.com',
    description='Attempt to write peg-parser for .hfss'
)
